#!/bin/sh

ROOT_DIRECTORY=$PWD

# These repositories cannot be written as an NPM dependency like pokemon-showdown, because it has directories not tracked by git (hence, as a NPM dependency, it won't have it)

test -d pokemon-showdown && (cd pokemon-showdown && git pull origin master) || git clone https://github.com/smogon/pokemon-showdown
cd pokemon-showdown && npm i 
node build 
cd ..

test -d pokemon-showdown-client && (cd pokemon-showdown-client && git pull origin master) || git clone https://github.com/smogon/pokemon-showdown-client
cd pokemon-showdown-client && npm i && rm -rf play.pokemonshowdown.com/js/battle-dex-search.js
node build
# Executing additionnal build to create assets for DexSearch
node build-tools/build-indexes

# additionnal steps :
# 1. Add Dex parameter to DexSearch for injection later
# 2. Add module.exports to battle-dex-search.js to allow module usage (intially not set for web client usage)

echo "\n" >> play.pokemonshowdown.com/js/battle-dex.js
echo "module.exports.toID = toID;" >> play.pokemonshowdown.com/js/battle-dex.js
echo "\n" >> play.pokemonshowdown.com/js/battle-dex-data.js
echo "module.exports.Ability = Ability;" >> play.pokemonshowdown.com/js/battle-dex-data.js
echo "module.exports.Item = Item;" >> play.pokemonshowdown.com/js/battle-dex-data.js
echo "module.exports.Move = Move;" >> play.pokemonshowdown.com/js/battle-dex-data.js
echo "module.exports.Species = Species;" >> play.pokemonshowdown.com/js/battle-dex-data.js
echo "module.exports.PureEffect = PureEffect;" >> play.pokemonshowdown.com/js/battle-dex-data.js

# Injecting assets in order for play.pokemonshowdown.com/js/battle-dex-search.js to work as a regular node.js module (and not like JS code from a web client)
# battle dex imports
sed -i "1s/^/const { Ability, Item, Move, Species, PureEffect } = require('.\/battle-dex-data');\n/" play.pokemonshowdown.com/js/battle-dex.js
# battle dex search imports
sed -i "1s/^/const { toID } = require('.\/battle-dex');\n/" play.pokemonshowdown.com/js/battle-dex-search.js
sed -i "2s/^/const { BattleTeambuilderTable } = require('..\/data\/teambuilder-tables');\n/" play.pokemonshowdown.com/js/battle-dex-search.js
sed -i "3s/^/const { BattleMovedex } = require('..\/data\/moves');\n/" play.pokemonshowdown.com/js/battle-dex-search.js
sed -i "4s/^/const { Dex } = require('../../../pokemon-showdown/dist/sim/index.js');\n/" play.pokemonshowdown.com/js/battle-dex-search.js

echo "\n" >> play.pokemonshowdown.com/js/battle-dex-search.js
echo "module.exports = DexSearch;" >> play.pokemonshowdown.com/js/battle-dex-search.js
