/*Formats*/ window.FormatNames = {
  gen9randombattle: "[Gen 9] Random Battle",
  gen9unratedrandombattle: "[Gen 9] Unrated Random Battle",
  gen9freeforallrandombattle: "[Gen 9] Free-For-All Random Battle",
  gen9randombattleblitz: "[Gen 9] Random Battle (Blitz)",
  gen9multirandombattle: "[Gen 9] Multi Random Battle",
  gen9ou: "[Gen 9] OU",
  gen9ubers: "[Gen 9] Ubers",
  gen9uu: "[Gen 9] UU",
  gen9ru: "[Gen 9] RU",
  gen9nu: "[Gen 9] NU",
  gen9pu: "[Gen 9] PU",
  gen9lc: "[Gen 9] LC",
  gen9monotype: "[Gen 9] Monotype",
  gen9monothreatfairy: "[Gen 9] Monothreat Fairy",
  gen91v1: "[Gen 9] 1v1",
  gen9anythinggoes: "[Gen 9] Anything Goes",
  gen9nfe: "[Gen 9] NFE",
  gen9zu: "[Gen 9] ZU",
  gen9lcuu: "[Gen 9] LC UU",
  gen9cap: "[Gen 9] CAP",
  gen9freeforall: "[Gen 9] Free-For-All",
  gen9battlestadiumsinglesregulationd:
    "[Gen 9] Battle Stadium Singles Regulation D",
  gen9battlestadiumsinglesregulatione:
    "[Gen 9] Battle Stadium Singles Regulation E",
  gen9dragonkingcup: "[Gen 9] Dragon King Cup",
  gen9customgame: "[Gen 9] Custom Game",
  gen9randomdoublesbattle: "[Gen 9] Random Doubles Battle",
  gen9doublesou: "[Gen 9] Doubles OU",
  gen9doublesubers: "[Gen 9] Doubles Ubers",
  gen9doublesuu: "[Gen 9] Doubles UU",
  gen9doubleslc: "[Gen 9] Doubles LC",
  gen92v2doubles: "[Gen 9] 2v2 Doubles",
  gen9vgc2023regulationd: "[Gen 9] VGC 2023 Regulation D",
  gen9vgc2023regulatione: "[Gen 9] VGC 2023 Regulation E",
  gen9vgc2023regulationebo3: "[Gen 9] VGC 2023 Regulation E (Bo3)",
  gen9doublescustomgame: "[Gen 9] Doubles Custom Game",
  gen3hoenngaiden: "[Gen 3] Hoenn Gaiden",
  gen8joltemonsrandombattle: "[Gen 8] JolteMons Random Battle",
  gen6nextou: "[Gen 6] NEXT OU",
  gen9paldeadexdraft: "[Gen 9] Paldea Dex Draft",
  gen9terapreviewpaldeadexdraft: "[Gen 9] Tera Preview Paldea Dex Draft",
  gen96v6doublesdraft: "[Gen 9] 6v6 Doubles Draft",
  gen94v4doublesdraft: "[Gen 9] 4v4 Doubles Draft",
  gen9natdexdraft: "[Gen 9] NatDex Draft",
  gen9terapreviewnatdexdraft: "[Gen 9] Tera Preview NatDex Draft",
  gen9natdex6v6doublesdraft: "[Gen 9] NatDex 6v6 Doubles Draft",
  gen9natdexlcdraft: "[Gen 9] NatDex LC Draft",
  gen9predlcpaldeadexdraft: "[Gen 9 Pre-DLC] Paldea Dex Draft",
  gen9predlcterapreviewpaldeadexdraft:
    "[Gen 9 Pre-DLC] Tera Preview Paldea Dex Draft",
  gen9predlcnatdexlcdraft: "[Gen 9 Pre-DLC] NatDex LC Draft",
  gen8galardexdraft: "[Gen 8] Galar Dex Draft",
  gen8natdexdraft: "[Gen 8] NatDex Draft",
  gen8natdex4v4doublesdraft: "[Gen 8] NatDex 4v4 Doubles Draft",
  gen7draft: "[Gen 7] Draft",
  gen6draft: "[Gen 6] Draft",
  gen9sharedpower: "[Gen 9] Shared Power",
  gen9proteanpalace: "[Gen 9] Protean Palace",
  gen9inheritance: "[Gen 9] Inheritance",
  gen9almostanyability: "[Gen 9] Almost Any Ability",
  gen9balancedhackmons: "[Gen 9] Balanced Hackmons",
  gen9godlygift: "[Gen 9] Godly Gift",
  gen9mixandmega: "[Gen 9] Mix and Mega",
  gen9stabmons: "[Gen 9] STABmons",
  gen9partnersincrime: "[Gen 9] Partners in Crime",
  gen6purehackmons: "[Gen 6] Pure Hackmons",
  gen9camomons: "[Gen 9] Camomons",
  gen9convergence: "[Gen 9] Convergence",
  gen9crossevolution: "[Gen 9] Cross Evolution",
  gen9fortemons: "[Gen 9] Fortemons",
  gen9franticfusions: "[Gen 9] Frantic Fusions",
  gen9fullpotential: "[Gen 9] Full Potential",
  gen9pokebilities: "[Gen 9] Pokebilities",
  gen9purehackmons: "[Gen 9] Pure Hackmons",
  gen9revelationmons: "[Gen 9] Revelationmons",
  gen9sharingiscaring: "[Gen 9] Sharing is Caring",
  gen9teradonation: "[Gen 9] Tera Donation",
  gen9thecardgame: "[Gen 9] The Card Game",
  gen9thelosersgame: "[Gen 9] The Loser's Game",
  gen9trademarked: "[Gen 9] Trademarked",
  gen9nationaldex: "[Gen 9] National Dex",
  gen9nationaldexubers: "[Gen 9] National Dex Ubers",
  gen9nationaldexuu: "[Gen 9] National Dex UU",
  gen9nationaldexru: "[Gen 9] National Dex RU",
  gen9nationaldexmonotype: "[Gen 9] National Dex Monotype",
  gen9nationaldexdoubles: "[Gen 9] National Dex Doubles",
  gen9nationaldexag: "[Gen 9] National Dex AG",
  gen9nationaldexbh: "[Gen 9] National Dex BH",
  gen8nationaldex: "[Gen 8] National Dex",
  gen8nationaldexuu: "[Gen 8] National Dex UU",
  gen8nationaldexmonotype: "[Gen 8] National Dex Monotype",
  gen9partnersincrimerandombattle: "[Gen 9] Partners in Crime Random Battle",
  gen9randomroulette: "[Gen 9] Random Roulette",
  gen9monotyperandombattle: "[Gen 9] Monotype Random Battle",
  gen9randombattlemayhem: "[Gen 9] Random Battle Mayhem",
  gen9computergeneratedteams: "[Gen 9] Computer-Generated Teams",
  gen9hackmonscup: "[Gen 9] Hackmons Cup",
  gen9doubleshackmonscup: "[Gen 9] Doubles Hackmons Cup",
  gen9brokencup: "[Gen 9] Broken Cup",
  gen9challengecup1v1: "[Gen 9] Challenge Cup 1v1",
  gen9challengecup2v2: "[Gen 9] Challenge Cup 2v2",
  gen9challengecup6v6: "[Gen 9] Challenge Cup 6v6",
  gen9metronomebattle: "[Gen 9] Metronome Battle",
  gen8randombattle: "[Gen 8] Random Battle",
  gen8randomdoublesbattle: "[Gen 8] Random Doubles Battle",
  gen8freeforallrandombattle: "[Gen 8] Free-For-All Random Battle",
  gen8multirandombattle: "[Gen 8] Multi Random Battle",
  gen8battlefactory: "[Gen 8] Battle Factory",
  gen8bssfactory: "[Gen 8] BSS Factory",
  gen8superstaffbros4: "[Gen 8] Super Staff Bros 4",
  gen8hackmonscup: "[Gen 8] Hackmons Cup",
  gen8metronomebattle: "[Gen 8] Metronome Battle",
  gen8cap1v1: "[Gen 8] CAP 1v1",
  gen8bdsprandombattle: "[Gen 8 BDSP] Random Battle",
  gen7randombattle: "[Gen 7] Random Battle",
  gen7randomdoublesbattle: "[Gen 7] Random Doubles Battle",
  gen7battlefactory: "[Gen 7] Battle Factory",
  gen7bssfactory: "[Gen 7] BSS Factory",
  gen7hackmonscup: "[Gen 7] Hackmons Cup",
  gen7letsgorandombattle: "[Gen 7 Let's Go] Random Battle",
  gen6randombattle: "[Gen 6] Random Battle",
  gen6battlefactory: "[Gen 6] Battle Factory",
  gen5randombattle: "[Gen 5] Random Battle",
  gen4randombattle: "[Gen 4] Random Battle",
  gen3randombattle: "[Gen 3] Random Battle",
  gen2randombattle: "[Gen 2] Random Battle",
  gen1randombattle: "[Gen 1] Random Battle",
  gen1challengecup: "[Gen 1] Challenge Cup",
  gen1hackmonscup: "[Gen 1] Hackmons Cup",
  gen6ubers: "[Gen 6] Ubers",
  gen3zu: "[Gen 3] ZU",
  gen3lc: "[Gen 3] LC",
  gen8ou: "[Gen 8] OU",
  gen7ou: "[Gen 7] OU",
  gen6ou: "[Gen 6] OU",
  gen5ou: "[Gen 5] OU",
  gen4ou: "[Gen 4] OU",
  gen3ou: "[Gen 3] OU",
  gen2ou: "[Gen 2] OU",
  gen1ou: "[Gen 1] OU",
  gen8doublesou: "[Gen 8] Doubles OU",
  gen7doublesou: "[Gen 7] Doubles OU",
  gen6doublesou: "[Gen 6] Doubles OU",
  gen5doublesou: "[Gen 5] Doubles OU",
  gen4doublesou: "[Gen 4] Doubles OU",
  gen3doublesou: "[Gen 3] Doubles OU",
  gen8ubers: "[Gen 8] Ubers",
  gen8uu: "[Gen 8] UU",
  gen8ru: "[Gen 8] RU",
  gen8nu: "[Gen 8] NU",
  gen8pu: "[Gen 8] PU",
  gen8lc: "[Gen 8] LC",
  gen8monotype: "[Gen 8] Monotype",
  gen81v1: "[Gen 8] 1v1",
  gen8anythinggoes: "[Gen 8] Anything Goes",
  gen8zu: "[Gen 8] ZU",
  gen8cap: "[Gen 8] CAP",
  gen8battlestadiumsingles: "[Gen 8] Battle Stadium Singles",
  gen8bdspou: "[Gen 8 BDSP] OU",
  gen8customgame: "[Gen 8] Custom Game",
  gen8doublesubers: "[Gen 8] Doubles Ubers",
  gen8doublesuu: "[Gen 8] Doubles UU",
  gen8vgc2022: "[Gen 8] VGC 2022",
  gen8vgc2021: "[Gen 8] VGC 2021",
  gen8vgc2020: "[Gen 8] VGC 2020",
  gen8bdspdoublesou: "[Gen 8 BDSP] Doubles OU",
  gen8bdspbattlefestivaldoubles: "[Gen 8 BDSP] Battle Festival Doubles",
  gen8doublescustomgame: "[Gen 8] Doubles Custom Game",
  gen7ubers: "[Gen 7] Ubers",
  gen7uu: "[Gen 7] UU",
  gen7ru: "[Gen 7] RU",
  gen7nu: "[Gen 7] NU",
  gen7pu: "[Gen 7] PU",
  gen7lc: "[Gen 7] LC",
  gen7monotype: "[Gen 7] Monotype",
  gen71v1: "[Gen 7] 1v1",
  gen7anythinggoes: "[Gen 7] Anything Goes",
  gen7zu: "[Gen 7] ZU",
  gen7cap: "[Gen 7] CAP",
  gen7battlespotsingles: "[Gen 7] Battle Spot Singles",
  gen7letsgoou: "[Gen 7 Let's Go] OU",
  gen7customgame: "[Gen 7] Custom Game",
  gen7doublesuu: "[Gen 7] Doubles UU",
  gen7vgc2019: "[Gen 7] VGC 2019",
  gen7vgc2018: "[Gen 7] VGC 2018",
  gen7vgc2017: "[Gen 7] VGC 2017",
  gen7battlespotdoubles: "[Gen 7] Battle Spot Doubles",
  gen7letsgodoublesou: "[Gen 7 Let's Go] Doubles OU",
  gen7doublescustomgame: "[Gen 7] Doubles Custom Game",
  gen6uu: "[Gen 6] UU",
  gen6ru: "[Gen 6] RU",
  gen6nu: "[Gen 6] NU",
  gen6pu: "[Gen 6] PU",
  gen6lc: "[Gen 6] LC",
  gen6monotype: "[Gen 6] Monotype",
  gen61v1: "[Gen 6] 1v1",
  gen6anythinggoes: "[Gen 6] Anything Goes",
  gen6zu: "[Gen 6] ZU",
  gen6cap: "[Gen 6] CAP",
  gen6battlespotsingles: "[Gen 6] Battle Spot Singles",
  gen6customgame: "[Gen 6] Custom Game",
  gen6vgc2016: "[Gen 6] VGC 2016",
  gen6vgc2015: "[Gen 6] VGC 2015",
  gen6vgc2014: "[Gen 6] VGC 2014",
  gen6battlespotdoubles: "[Gen 6] Battle Spot Doubles",
  gen6doublescustomgame: "[Gen 6] Doubles Custom Game",
  gen6battlespottriples: "[Gen 6] Battle Spot Triples",
  gen6triplescustomgame: "[Gen 6] Triples Custom Game",
  gen5ubers: "[Gen 5] Ubers",
  gen5uu: "[Gen 5] UU",
  gen5ru: "[Gen 5] RU",
  gen5nu: "[Gen 5] NU",
  gen5pu: "[Gen 5] PU",
  gen5lc: "[Gen 5] LC",
  gen5monotype: "[Gen 5] Monotype",
  gen51v1: "[Gen 5] 1v1",
  gen5zu: "[Gen 5] ZU",
  gen5cap: "[Gen 5] CAP",
  gen5gbusingles: "[Gen 5] GBU Singles",
  gen5customgame: "[Gen 5] Custom Game",
  gen5vgc2013: "[Gen 5] VGC 2013",
  gen5vgc2012: "[Gen 5] VGC 2012",
  gen5vgc2011: "[Gen 5] VGC 2011",
  gen5doublescustomgame: "[Gen 5] Doubles Custom Game",
  gen5triplescustomgame: "[Gen 5] Triples Custom Game",
  gen4ubers: "[Gen 4] Ubers",
  gen4uu: "[Gen 4] UU",
  gen4nu: "[Gen 4] NU",
  gen4pu: "[Gen 4] PU",
  gen4lc: "[Gen 4] LC",
  gen4anythinggoes: "[Gen 4] Anything Goes",
  gen41v1: "[Gen 4] 1v1",
  gen4zu: "[Gen 4] ZU",
  gen4cap: "[Gen 4] CAP",
  gen4customgame: "[Gen 4] Custom Game",
  gen4vgc2010: "[Gen 4] VGC 2010",
  gen4vgc2009: "[Gen 4] VGC 2009",
  gen4doublescustomgame: "[Gen 4] Doubles Custom Game",
  gen3ubers: "[Gen 3] Ubers",
  gen3uu: "[Gen 3] UU",
  gen3nu: "[Gen 3] NU",
  gen3pu: "[Gen 3] PU",
  gen31v1: "[Gen 3] 1v1",
  gen3customgame: "[Gen 3] Custom Game",
  gen3doublescustomgame: "[Gen 3] Doubles Custom Game",
  gen2ubers: "[Gen 2] Ubers",
  gen2uu: "[Gen 2] UU",
  gen2nu: "[Gen 2] NU",
  gen21v1: "[Gen 2] 1v1",
  gen2nintendocup2000: "[Gen 2] Nintendo Cup 2000",
  gen2stadiumou: "[Gen 2] Stadium OU",
  gen2customgame: "[Gen 2] Custom Game",
  gen1ubers: "[Gen 1] Ubers",
  gen1uu: "[Gen 1] UU",
  gen1nu: "[Gen 1] NU",
  gen1pu: "[Gen 1] PU",
  gen11v1: "[Gen 1] 1v1",
  gen1japaneseou: "[Gen 1] Japanese OU",
  gen1stadiumou: "[Gen 1] Stadium OU",
  gen1tradebacksou: "[Gen 1] Tradebacks OU",
  gen1nintendocup1997: "[Gen 1] Nintendo Cup 1997",
  gen1customgame: "[Gen 1] Custom Game",
};
