/*Formats*/ window.FormatNames = {
  gen9ou: "[Gen 9] OU",
  gen9ubers: "[Gen 9] Ubers",
  gen9uu: "[Gen 9] UU",
  gen9ru: "[Gen 9] RU",
  gen9nu: "[Gen 9] NU",
  gen9pu: "[Gen 9] PU",
  gen9lc: "[Gen 9] LC",
  gen9monotype: "[Gen 9] Monotype",
  gen9bssregg: "[Gen 9] BSS Reg G",
  gen9bssregi: "[Gen 9] BSS Reg I",
  gen9doublesou: "[Gen 9] Doubles OU",
  gen9doublesubers: "[Gen 9] Doubles Ubers",
  gen9doublesuu: "[Gen 9] Doubles UU",
  gen9doubleslc: "[Gen 9] Doubles LC",
  gen9vgc2023regd: "[Gen 9] VGC 2023 Reg D",
  gen9vgc2024regg: "[Gen 9] VGC 2024 Reg G",
  gen9vgc2025regi: "[Gen 9] VGC 2025 Reg I",
  gen9vgc2025regibo3: "[Gen 9] VGC 2025 Reg I (Bo3)",
  gen91v1: "[Gen 9] 1v1",
  gen92v2doubles: "[Gen 9] 2v2 Doubles",
  gen9ubersuu: "[Gen 9] Ubers UU",
  gen9zu: "[Gen 9] ZU",
  gen9lcuu: "[Gen 9] LC UU",
  gen9nfe: "[Gen 9] NFE",
  gen9fusionevolutionrandombattle: "[Gen 9] Fusion Evolution Random Battle",
  gen9tiershift: "[Gen 9] Tier Shift",
  gen9nationaldex1v1: "[Gen 9] National Dex 1v1",
  gen8nationaldexru: "[Gen 8] National Dex RU",
  gen8nationaldexdoubles: "[Gen 8] National Dex Doubles",
  gen8dlc1nationaldexag: "[Gen 8 DLC 1] National Dex AG",
  gen3uu: "[Gen 3] UU",
  gen6ru: "[Gen 6] RU",
  gen4pu: "[Gen 4] PU",
  gen8ou: "[Gen 8] OU",
  gen7ou: "[Gen 7] OU",
  gen6ou: "[Gen 6] OU",
  gen5ou: "[Gen 5] OU",
  gen4ou: "[Gen 4] OU",
  gen3ou: "[Gen 3] OU",
  gen2ou: "[Gen 2] OU",
  gen1ou: "[Gen 1] OU",
  gen8doublesou: "[Gen 8] Doubles OU",
  gen7doublesou: "[Gen 7] Doubles OU",
  gen6doublesou: "[Gen 6] Doubles OU",
  gen5doublesou: "[Gen 5] Doubles OU",
  gen4doublesou: "[Gen 4] Doubles OU",
  gen3doublesou: "[Gen 3] Doubles OU",
  gen8ubers: "[Gen 8] Ubers",
  gen8uu: "[Gen 8] UU",
  gen8ru: "[Gen 8] RU",
  gen8nu: "[Gen 8] NU",
  gen8pu: "[Gen 8] PU",
  gen8lc: "[Gen 8] LC",
  gen8monotype: "[Gen 8] Monotype",
  gen81v1: "[Gen 8] 1v1",
  gen8zu: "[Gen 8] ZU",
  gen8battlestadiumsingles: "[Gen 8] Battle Stadium Singles",
  gen8bdspou: "[Gen 8 BDSP] OU",
  gen8bdspubers: "[Gen 8 BDSP] Ubers",
  gen8doublesubers: "[Gen 8] Doubles Ubers",
  gen8doublesuu: "[Gen 8] Doubles UU",
  gen8vgc2022: "[Gen 8] VGC 2022",
  gen8vgc2021: "[Gen 8] VGC 2021",
  gen8vgc2020: "[Gen 8] VGC 2020",
  gen8bdspdoublesou: "[Gen 8 BDSP] Doubles OU",
  gen7ubers: "[Gen 7] Ubers",
  gen7uu: "[Gen 7] UU",
  gen7ru: "[Gen 7] RU",
  gen7nu: "[Gen 7] NU",
  gen7pu: "[Gen 7] PU",
  gen7lc: "[Gen 7] LC",
  gen7monotype: "[Gen 7] Monotype",
  gen71v1: "[Gen 7] 1v1",
  gen7zu: "[Gen 7] ZU",
  gen7letsgoou: "[Gen 7 Let's Go] OU",
  gen7doublesuu: "[Gen 7] Doubles UU",
  gen7vgc2019: "[Gen 7] VGC 2019",
  gen7vgc2018: "[Gen 7] VGC 2018",
  gen7vgc2017: "[Gen 7] VGC 2017",
  gen6ubers: "[Gen 6] Ubers",
  gen6uu: "[Gen 6] UU",
  gen6nu: "[Gen 6] NU",
  gen6pu: "[Gen 6] PU",
  gen6lc: "[Gen 6] LC",
  gen6monotype: "[Gen 6] Monotype",
  gen61v1: "[Gen 6] 1v1",
  gen6zu: "[Gen 6] ZU",
  gen5ubers: "[Gen 5] Ubers",
  gen5uu: "[Gen 5] UU",
  gen5ru: "[Gen 5] RU",
  gen5nu: "[Gen 5] NU",
  gen5pu: "[Gen 5] PU",
  gen5lc: "[Gen 5] LC",
  gen5monotype: "[Gen 5] Monotype",
  gen51v1: "[Gen 5] 1v1",
  gen5zu: "[Gen 5] ZU",
  gen5cap: "[Gen 5] CAP",
  gen4ubers: "[Gen 4] Ubers",
  gen4uu: "[Gen 4] UU",
  gen4nu: "[Gen 4] NU",
  gen4lc: "[Gen 4] LC",
  gen41v1: "[Gen 4] 1v1",
  gen4zu: "[Gen 4] ZU",
  gen3ubers: "[Gen 3] Ubers",
  gen3ru: "[Gen 3] RU",
  gen3nu: "[Gen 3] NU",
  gen3pu: "[Gen 3] PU",
  gen3lc: "[Gen 3] LC",
  gen31v1: "[Gen 3] 1v1",
  gen3uubl: "[Gen 3] UUBL",
  gen3zu: "[Gen 3] ZU",
  gen3orrecolosseum: "[Gen 3] Orre Colosseum",
  gen2ubers: "[Gen 2] Ubers",
  gen2uu: "[Gen 2] UU",
  gen2nu: "[Gen 2] NU",
  gen2pu: "[Gen 2] PU",
  gen21v1: "[Gen 2] 1v1",
  gen2zu: "[Gen 2] ZU",
  gen1ubers: "[Gen 1] Ubers",
  gen1uu: "[Gen 1] UU",
  gen1nu: "[Gen 1] NU",
  gen1pu: "[Gen 1] PU",
  gen1zu: "[Gen 1] ZU",
  gen1lc: "[Gen 1] LC",
  gen11v1: "[Gen 1] 1v1",
};
