const rejectedNames = {
  gen9vgc2025reggbo3: "[Gen 9] VGC 2025 Reg G (Bo3)",
  gen9randombattle: "[Gen 9] Random Battle",
  gen9unratedrandombattle: "[Gen 9] Unrated Random Battle",
  gen9freeforallrandombattle: "[Gen 9] Free-For-All Random Battle",
  gen9randombattleblitz: "[Gen 9] Random Battle (Blitz)",
  gen9multirandombattle: "[Gen 9] Multi Random Battle",
  gen9cap: "[Gen 9] CAP",
  gen9customgame: "[Gen 9] Custom Game",
  gen9randomdoublesbattle: "[Gen 9] Random Doubles Battle",
  gen9doublescustomgame: "[Gen 9] Doubles Custom Game",
  gen9anythinggoes: "[Gen 9] Anything Goes",
  gen9freeforall: "[Gen 9] Free-For-All",
  gen9badnboosted: "[Gen 9] Bad 'n Boosted",
  gen9ccapm2024randombattle: "[Gen 9] CCAPM 2024 Random Battle",
  gen9draft: "[Gen 9] Draft",
  gen96v6doublesdraft: "[Gen 9] 6v6 Doubles Draft",
  gen94v4doublesdraft: "[Gen 9] 4v4 Doubles Draft",
  gen9natdexdraft: "[Gen 9] NatDex Draft",
  gen9natdex6v6doublesdraft: "[Gen 9] NatDex 6v6 Doubles Draft",
  gen9natdexlcdraft: "[Gen 9] NatDex LC Draft",
  gen9littlecolosseumlc: "[Gen 9] Little Colosseum LC",
  gen8galardexdraft: "[Gen 8] Galar Dex Draft",
  gen8natdexdraft: "[Gen 8] NatDex Draft",
  gen8natdex4v4doublesdraft: "[Gen 8] NatDex 4v4 Doubles Draft",
  gen7draft: "[Gen 7] Draft",
  gen6draft: "[Gen 6] Draft",
  gen5draft: "[Gen 5] Draft",
  gen4draft: "[Gen 4] Draft",
  gen3draft: "[Gen 3] Draft",
  gen9trademarked: "[Gen 9] Trademarked",
  gen9partnersincrime: "[Gen 9] Partners in Crime",
  gen9almostanyability: "[Gen 9] Almost Any Ability",
  gen9balancedhackmons: "[Gen 9] Balanced Hackmons",
  gen9godlygift: "[Gen 9] Godly Gift",
  gen9mixandmega: "[Gen 9] Mix and Mega",
  gen9sharedpower: "[Gen 9] Shared Power",
  gen9stabmons: "[Gen 9] STABmons",
  gen7purehackmons: "[Gen 7] Pure Hackmons",
  gen912switch: "[Gen 9] 1-2 Switch",
  gen9350cup: "[Gen 9] 350 Cup",
  gen9alphabetcup: "[Gen 9] Alphabet Cup",
  gen9camomons: "[Gen 9] Camomons",
  gen9categoryswap: "[Gen 9] Category Swap",
  gen9convergence: "[Gen 9] Convergence",
  gen9crossevolution: "[Gen 9] Cross Evolution",
  gen9ferventimpersonation: "[Gen 9] Fervent Impersonation",
  gen9foresighters: "[Gen 9] Foresighters",
  gen9formemons: "[Gen 9] Formemons",
  gen9fortemons: "[Gen 9] Fortemons",
  gen9franticfusions: "[Gen 9] Frantic Fusions",
  gen9fullpotential: "[Gen 9] Full Potential",
  gen9inheritance: "[Gen 9] Inheritance",
  gen9inverse: "[Gen 9] Inverse",
  gen9natureswap: "[Gen 9] Nature Swap",
  gen9passiveaggressive: "[Gen 9] Passive Aggressive",
  gen9pokebilities: "[Gen 9] Pokebilities",
  gen9pokemoves: "[Gen 9] Pokemoves",
  gen9purehackmons: "[Gen 9] Pure Hackmons",
  gen9relayrace: "[Gen 9] Relay Race",
  gen9revelationmons: "[Gen 9] Revelationmons",
  gen9sharingiscaring: "[Gen 9] Sharing is Caring",
  gen9teradonation: "[Gen 9] Tera Donation",
  gen9thecardgame: "[Gen 9] The Card Game",
  gen9thelosersgame: "[Gen 9] The Loser's Game",
  gen9triples: "[Gen 9] Triples",
  gen9typesplit: "[Gen 9] Type Split",
  gen6purehackmons: "[Gen 6] Pure Hackmons",
  gen9nationaldex: "[Gen 9] National Dex",
  gen8nationaldex: "[Gen 8] National Dex",
  gen9nationaldex35pokes: "[Gen 9] National Dex 35 Pokes",
  gen9nationaldexubers: "[Gen 9] National Dex Ubers",
  gen9nationaldexuu: "[Gen 9] National Dex UU",
  gen9nationaldexru: "[Gen 9] National Dex RU",
  gen9nationaldexlc: "[Gen 9] National Dex LC",
  gen9nationaldexmonotype: "[Gen 9] National Dex Monotype",
  gen9nationaldexdoubles: "[Gen 9] National Dex Doubles",
  gen9nationaldexdoublesubers: "[Gen 9] National Dex Doubles Ubers",
  gen9nationaldexubersuu: "[Gen 9] National Dex Ubers UU",
  gen9nationaldexag: "[Gen 9] National Dex AG",
  gen9nationaldexaaa: "[Gen 9] National Dex AAA",
  gen9nationaldexbh: "[Gen 9] National Dex BH",
  gen9nationaldexgodlygift: "[Gen 9] National Dex Godly Gift",
  gen9nationaldexstabmons: "[Gen 9] National Dex STABmons",
  gen8nationaldexuu: "[Gen 8] National Dex UU",
  gen8nationaldexmonotype: "[Gen 8] National Dex Monotype",
  gen9partnersincrimerandombattle6moves:
    "[Gen 9] Partners in Crime Random Battle (6 Moves)",
  gen9randomroulette: "[Gen 9] Random Roulette",
  gen9monkeyspawrandombattle: "[Gen 9] Monkey's Paw Random Battle",
  gen9superstaffbrosultimate: "[Gen 9] Super Staff Bros Ultimate",
  gen9monotyperandombattle: "[Gen 9] Monotype Random Battle",
  gen9randombattlesharedpowerb12p6:
    "[Gen 9] Random Battle (Shared Power, B12P6)",
  gen9randombattlemayhem: "[Gen 9] Random Battle Mayhem",
  gen9battlefactory: "[Gen 9] Battle Factory",
  gen9bssfactory: "[Gen 9] BSS Factory",
  gen9draftfactory: "[Gen 9] Draft Factory",
  gen9babyrandombattle: "[Gen 9] Baby Random Battle",
  gen9computergeneratedteams: "[Gen 9] Computer-Generated Teams",
  gen9hackmonscup: "[Gen 9] Hackmons Cup",
  gen9doubleshackmonscup: "[Gen 9] Doubles Hackmons Cup",
  gen9brokencup: "[Gen 9] Broken Cup",
  gen9challengecup1v1: "[Gen 9] Challenge Cup 1v1",
  gen9challengecup2v2: "[Gen 9] Challenge Cup 2v2",
  gen9challengecup6v6: "[Gen 9] Challenge Cup 6v6",
  gen9metronomebattle: "[Gen 9] Metronome Battle",
  gen8randombattle: "[Gen 8] Random Battle",
  gen8randomdoublesbattle: "[Gen 8] Random Doubles Battle",
  gen8freeforallrandombattle: "[Gen 8] Free-For-All Random Battle",
  gen8multirandombattle: "[Gen 8] Multi Random Battle",
  gen8battlefactory: "[Gen 8] Battle Factory",
  gen8bssfactory: "[Gen 8] BSS Factory",
  gen8hackmonscup: "[Gen 8] Hackmons Cup",
  gen8cap1v1: "[Gen 8] CAP 1v1",
  gen8bdsprandombattle: "[Gen 8 BDSP] Random Battle",
  gen7randombattle: "[Gen 7] Random Battle",
  gen7battlefactory: "[Gen 7] Battle Factory",
  gen7bssfactory: "[Gen 7] BSS Factory",
  gen7hackmonscup: "[Gen 7] Hackmons Cup",
  gen7letsgorandombattle: "[Gen 7 Let's Go] Random Battle",
  gen6randombattle: "[Gen 6] Random Battle",
  gen6battlefactory: "[Gen 6] Battle Factory",
  gen5randombattle: "[Gen 5] Random Battle",
  gen4randombattle: "[Gen 4] Random Battle",
  gen3randombattle: "[Gen 3] Random Battle",
  gen2randombattle: "[Gen 2] Random Battle",
  gen1randombattle: "[Gen 1] Random Battle",
  gen1challengecup: "[Gen 1] Challenge Cup",
  gen1hackmonscup: "[Gen 1] Hackmons Cup",
  gen3adv200: "[Gen 3] ADV 200",
  gen8anythinggoes: "[Gen 8] Anything Goes",
  gen8cap: "[Gen 8] CAP",
  gen8customgame: "[Gen 8] Custom Game",
  gen8bdspbattlefestivaldoubles: "[Gen 8 BDSP] Battle Festival Doubles",
  gen8doublescustomgame: "[Gen 8] Doubles Custom Game",
  gen7anythinggoes: "[Gen 7] Anything Goes",
  gen7cap: "[Gen 7] CAP",
  gen7battlespotsingles: "[Gen 7] Battle Spot Singles",
  gen7customgame: "[Gen 7] Custom Game",
  gen7battlespotdoubles: "[Gen 7] Battle Spot Doubles",
  gen7letsgodoublesou: "[Gen 7 Let's Go] Doubles OU",
  gen7doublescustomgame: "[Gen 7] Doubles Custom Game",
  gen6anythinggoes: "[Gen 6] Anything Goes",
  gen6cap: "[Gen 6] CAP",
  gen6battlespotsingles: "[Gen 6] Battle Spot Singles",
  gen6customgame: "[Gen 6] Custom Game",
  gen6vgc2016: "[Gen 6] VGC 2016",
  gen6vgc2015: "[Gen 6] VGC 2015",
  gen6vgc2014: "[Gen 6] VGC 2014",
  gen6battlespotdoubles: "[Gen 6] Battle Spot Doubles",
  gen6doublescustomgame: "[Gen 6] Doubles Custom Game",
  gen6battlespottriples: "[Gen 6] Battle Spot Triples",
  gen6triplescustomgame: "[Gen 6] Triples Custom Game",
  gen5bw1ou: "[Gen 5] BW1 OU",
  gen5gbusingles: "[Gen 5] GBU Singles",
  gen5customgame: "[Gen 5] Custom Game",
  gen5vgc2013: "[Gen 5] VGC 2013",
  gen5vgc2012: "[Gen 5] VGC 2012",
  gen5vgc2011: "[Gen 5] VGC 2011",
  gen5doublescustomgame: "[Gen 5] Doubles Custom Game",
  gen5triplescustomgame: "[Gen 5] Triples Custom Game",
  gen4anythinggoes: "[Gen 4] Anything Goes",
  gen4customgame: "[Gen 4] Custom Game",
  gen4vgc2010: "[Gen 4] VGC 2010",
  gen4vgc2009: "[Gen 4] VGC 2009",
  gen4doublescustomgame: "[Gen 4] Doubles Custom Game",
  gen4cap: "[Gen 4] CAP",
  gen3customgame: "[Gen 3] Custom Game",
  gen3doublescustomgame: "[Gen 3] Doubles Custom Game",
  gen2nc2000: "[Gen 2] NC 2000",
  gen2stadiumou: "[Gen 2] Stadium OU",
  gen2customgame: "[Gen 2] Custom Game",
  gen1japaneseou: "[Gen 1] Japanese OU",
  gen1stadiumou: "[Gen 1] Stadium OU",
  gen1tradebacksou: "[Gen 1] Tradebacks OU",
  gen1nc1997: "[Gen 1] NC 1997",
  gen1customgame: "[Gen 1] Custom Game",
  gen2gscdoubles: "[Gen 2] GSC Doubles",
  gen7randombattleapexabilities: "[Gen 7] Random Battle (Apex Abilities)",
  gen9pickyourteamrandombattle: "[Gen 9] Pick-Your-Team Random Battle",
};

module.exports = rejectedNames;
